# -*- coding: utf-8 -*-
"""
Created on Tue May 19 08:11:52 2020

@author: debth
"""

import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
import os

# peak verification 
# File setup for data and results################################
fname ='merged-raw-TDCAEXD332886Z-paire-0'
ddir = '../results/peaks/'
rdir = '../results/peaks/Verification/'
idir = '../results/CSV/merged/'
fname_peaks = 'picks_denoised-TDCAEXD332886Z-paire-0.csv'


# load the data file 
print ('Processing file : '+idir+fname+'.csv')
data_brute=np.genfromtxt(idir+fname+'.csv',delimiter=',')
m,n = data_brute.shape
traces_brute = data_brute[:,1:n]
nsample,ntraces_brute = traces_brute.shape
data_peaks = np.genfromtxt(ddir+fname_peaks,delimiter=',')

#Standart Deviation methode 1 (fonctionne pas, c'est un essais)

def sigma(traces_brute):
    positives = [m for m in traces_brute if m >= 0]
    sq_err=[]
    if positives:
        mean = sum(positives) / len(positives)
        diff = ((sum([abs(i - mean)**2 for i in positives]))/(len(positives)))**(0.5)
        for i in positives:
            if (abs(i - mean)) > (diff*3):
                sq_err.append(0)
            else:
                sq_err.append(i)
    else:
        return [0]
    return sq_err

G = map(sigma,traces_brute)
print (G) 

#Standart Deviation methode 2 (bloquer car je n'arrive pas a faire de graphique fonctionnel (tuple) et il y'a une erreur dans data_brute que j'arrive pas faire sortir)

a = data_brute[:,1:n]

def sdevs(a):
    sds = [0]
    n = 1
    sum_x = a[0]
    sum_x_squared = a[0]**2

    for x in a[1:]:
        sum_x += x
        sum_x_squared += x**2
        n += 1
        sd = sqrt(n/(n-1)*(sum_x_squared/n - (sum_x/n)**2))
        sds.append(sd)
    return sds

sds = sdevs(a)
print(sds[450])
result = sds[0,2048]

plt.plot(sds[:,0],sds[:,1],data_peaks[:,0],data_peaks[:,1],'+')
plt.show()
